/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#001e40",
        "secondary-fixed-dim": "#c7c6cb",
        "surface-bright": "#fcf8fb",
        "surface-container-highest": "#e4e2e4",
        "secondary": "#5e5e63",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "border-subtle": "#D2D2D7",
        "on-tertiary-fixed-variant": "#723610",
        "success": "#24A249",
        "secondary-container": "#e0dfe4",
        "outline": "#737780",
        "tertiary-container": "#592300",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#1f477b",
        "surface": "#fcf8fb",
        "error": "#E22126",
        "inverse-on-surface": "#f3f0f2",
        "on-primary-container": "#799dd6",
        "on-surface": "#1b1b1d",
        "surface-dim": "#dcd9dc",
        "surface-container-low": "#f6f3f5",
        "tertiary-fixed-dim": "#ffb690",
        "surface-container": "#f0edef",
        "tertiary": "#381300",
        "inverse-surface": "#303032",
        "surface-tint": "#3a5f94",
        "surface-container-high": "#eae7ea",
        "on-surface-variant": "#43474f",
        "error-container": "#ffdad6",
        "surface-primary": "#FBFBFD",
        "on-secondary-fixed-variant": "#46464b",
        "surface-variant": "#e4e2e4",
        "background": "#fcf8fb",
        "on-tertiary-container": "#d8885c",
        "on-background": "#1b1b1d",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "primary-fixed": "#d5e3ff",
        "warning": "#FF9F0A",
        "primary-container": "#003366",
        "surface-secondary": "#F5F5F7",
        "primary-fixed-dim": "#a7c8ff",
        "secondary-fixed": "#e3e2e7",
        "tertiary-fixed": "#ffdbca",
        "on-secondary-fixed": "#1a1b1f",
        "on-secondary-container": "#626267",
        "inverse-primary": "#a7c8ff",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#341100",
        "on-primary-fixed": "#001b3c",
        "outline-variant": "#c3c6d1",
        // Admin Dashboard Phase 1 Theme Tokens
        "page-bg": "#141416",
        "card-bg": "#1e1f24",
        "card-border": "#2a2b31",
        "accent-indigo": "#6366f1",
        "accent-violet": "#8b5cf6",
        "hero-purple": "#7c3aed",
        "hero-lavender": "#a78bfa",
        "delta-green": "#10b981",
        "delta-red": "#ef4444",
        "muted-label": "#9ca3af",
        "rail-dark": "#111113",
        "sidebar-dark": "#17181c",
        "topbar-dark": "#17181c",
        // Semantic theme tokens for light / dark
        dash: {
          page: "var(--dash-page)",
          card: "var(--dash-card)",
          border: "var(--dash-border)",
          rail: "var(--dash-rail)",
          sidebar: "var(--dash-sidebar)",
          topbar: "var(--dash-topbar)",
          text: "var(--dash-text)",
          muted: "var(--dash-muted)",
        }
      },
      fontFamily: {
        sans: ['Inter', 'Geist', 'Outfit', 'system-ui', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        geist: ['Geist', 'sans-serif'],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "card": "12px",
        "full": "9999px"
      },
      spacing: {
        "element-gap-sm": "8px",
        "gutter": "24px",
        "widget-padding": "24px",
        "element-gap-md": "16px",
        "container-margin": "32px"
      }
    },
  },
  plugins: [],
}
