/home/azureuser/snist_attendance/*.log
/home/azureuser/snist_attendance/backend/*.log
{
    su azureuser azureuser
    daily
    missingok
    rotate 7
    compress
    delaycompress
    notifempty
    copytruncate
    maxsize 50M
}
